export interface ScrapeSourceConfig {
  id: string;
  name: string;
  url: string;
  searchUrl: string;
  logoEmoji: string;
  category: 'major' | 'specialist' | 'online' | 'broker';
  listingsEstimate: string;
  description: string;
  enabled: boolean;
}

export const UK_BUSINESS_SOURCES: ScrapeSourceConfig[] = [
  // MAJOR MARKETPLACES
  {
    id: 'rightbiz',
    name: 'Rightbiz',
    url: 'https://www.rightbiz.co.uk',
    searchUrl: 'https://www.rightbiz.co.uk/businesses-for-sale',
    logoEmoji: '🟢',
    category: 'major',
    listingsEstimate: '10,000+',
    description: 'UK\'s largest business for sale marketplace. 400+ agents, £10B+ in listings.',
    enabled: true,
  },
  {
    id: 'daltons',
    name: 'Daltons Business',
    url: 'https://www.daltonsbusiness.com',
    searchUrl: 'https://www.daltonsbusiness.com/buy/business-for-sale',
    logoEmoji: '🔵',
    category: 'major',
    listingsEstimate: '20,000+',
    description: 'UK\'s leading site for buying/selling businesses. 90K buyers weekly.',
    enabled: true,
  },
  {
    id: 'businessesforsale',
    name: 'BusinessesForSale.com',
    url: 'https://uk.businessesforsale.com',
    searchUrl: 'https://uk.businessesforsale.com/uk/search/businesses-for-sale',
    logoEmoji: '🟠',
    category: 'major',
    listingsEstimate: '13,600+',
    description: 'Global marketplace with strong UK coverage. 58K+ listings worldwide.',
    enabled: true,
  },
  {
    id: 'businesssale',
    name: 'Business Sale Report',
    url: 'https://www.business-sale.com',
    searchUrl: 'https://www.business-sale.com/businesses-for-sale',
    logoEmoji: '🟣',
    category: 'major',
    listingsEstimate: '5,000+',
    description: 'Most established UK business marketplace. 5K+ live listings.',
    enabled: true,
  },
  {
    id: 'dealopportunities',
    name: 'Deal Opportunities',
    url: 'https://www.dealopportunities.co.uk',
    searchUrl: 'https://www.dealopportunities.co.uk/businesses-for-sale',
    logoEmoji: '🟡',
    category: 'major',
    listingsEstimate: '500+',
    description: 'Premium deal marketplace. 15K+ professionals receiving alerts.',
    enabled: true,
  },
  // SPECIALIST / BROKER
  {
    id: 'bizdaq',
    name: 'Bizdaq',
    url: 'https://www.bizdaq.com',
    searchUrl: 'https://www.bizdaq.com/businesses-for-sale',
    logoEmoji: '🔷',
    category: 'specialist',
    listingsEstimate: '3,000+',
    description: 'Free business valuation tool. Strong SME marketplace.',
    enabled: true,
  },
  {
    id: 'nationwidebusinesses',
    name: 'Nationwide Businesses',
    url: 'https://www.nationwidebusinesses.co.uk',
    searchUrl: 'https://www.nationwidebusinesses.co.uk/businesses-for-sale',
    logoEmoji: '🏴',
    category: 'broker',
    listingsEstimate: '500+',
    description: 'Small business specialist — shops, cafes, salons.',
    enabled: true,
  },
  {
    id: 'intelligent',
    name: 'Intelligent Business Partners',
    url: 'https://www.intelligent.co.uk',
    searchUrl: 'https://www.intelligent.co.uk/businesses-for-sale',
    logoEmoji: '🧠',
    category: 'broker',
    listingsEstimate: '200+',
    description: 'Award-winning SME broker agency.',
    enabled: true,
  },
  {
    id: 'businessbuyers',
    name: 'Business Buyers',
    url: 'https://www.businessbuyers.co.uk',
    searchUrl: 'https://www.businessbuyers.co.uk/listings',
    logoEmoji: '🤝',
    category: 'broker',
    listingsEstimate: '300+',
    description: 'Fast-growing SME buying/selling network.',
    enabled: true,
  },
  {
    id: 'smergers',
    name: 'SMERGERS',
    url: 'https://www.smergers.com',
    searchUrl: 'https://www.smergers.com/businesses-for-sale-and-investment-in-uk/c83b/',
    logoEmoji: '🤖',
    category: 'specialist',
    listingsEstimate: '400+',
    description: 'AI-powered M&A platform. Cross-border deals.',
    enabled: true,
  },
  // ONLINE / DIGITAL
  {
    id: 'flippa',
    name: 'Flippa',
    url: 'https://flippa.com',
    searchUrl: 'https://flippa.com/online-businesses-united-kingdom',
    logoEmoji: '💻',
    category: 'online',
    listingsEstimate: '1,000+',
    description: '#1 marketplace for online businesses & websites.',
    enabled: true,
  },
  {
    id: 'bizquest',
    name: 'BizQuest',
    url: 'https://www.bizquest.com',
    searchUrl: 'https://www.bizquest.com/businesses-for-sale-in-united-kingdom/',
    logoEmoji: '🔍',
    category: 'online',
    listingsEstimate: '200+',
    description: 'International marketplace with UK section.',
    enabled: true,
  },
  {
    id: 'buymybiz',
    name: 'BuyMyBiz',
    url: 'https://www.buymybiz.co.uk',
    searchUrl: 'https://www.buymybiz.co.uk/businesses-for-sale',
    logoEmoji: '💼',
    category: 'broker',
    listingsEstimate: '150+',
    description: 'SME business broker — valuations and sales.',
    enabled: true,
  },
  {
    id: 'transworld',
    name: 'Transworld Business Advisors',
    url: 'https://www.tworld.com',
    searchUrl: 'https://www.tworld.com/locations/united-kingdom/',
    logoEmoji: '🌍',
    category: 'broker',
    listingsEstimate: '100+',
    description: 'Global franchise broker with UK presence.',
    enabled: true,
  },
  {
    id: 'hiltonsmythe',
    name: 'Hilton Smythe',
    url: 'https://www.hiltonsmythe.com',
    searchUrl: 'https://www.hiltonsmythe.com/businesses-for-sale/',
    logoEmoji: '🏛️',
    category: 'broker',
    listingsEstimate: '200+',
    description: 'Full-service business broker. Valuations, sales, advisory.',
    enabled: true,
  },
];

export const SOURCE_CATEGORIES = {
  major: { label: 'Major Marketplaces', description: 'Highest volume, broadest coverage' },
  specialist: { label: 'Specialist Platforms', description: 'Niche or AI-powered' },
  online: { label: 'Online/Digital', description: 'Websites and online businesses' },
  broker: { label: 'Broker Networks', description: 'Agency-listed opportunities' },
};
